spring.application.name=cloudShareapi
spring.data.mongodb.uri=mongodb+srv://venkateshbadamdurga_db_user:Venky%402007@cluster0.her7e05.mongodb.net/CloudShare?retryWrites=true&w=majority&appName=Cluster0
server.servlet.context-path=/api/v1.0

spring.data.mongodb.auto-index-creation=true
server.port=9090

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

clerk.issuer=https://feasible-flea-68.clerk.accounts.dev
clerk.jwks-url=https://feasible-flea-68.clerk.accounts.dev/.well-known/jwks.json
clerk.webhook.secret=whsec_W64npDrMB8TJFyMUswP2s82MYU7nUDno

#file upload configuration
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=25MB

razorpay.key.id=rzp_test_RRjF0Z7hQ5OIIM
razorpay.key.secret=MFLWl57VLbI3X8xGko7tCqdm